sonar.projectKey=python-poc-demo
sonar.sources=.
sonar.exclusions=**/venv/**,**/node_modules/**
sonar.host.url=http://localhost:9000
sonar.token=squ_098f2d257eab6dae7f86f55b1fe08f024670cd59
sonar.qualitygate.wait=true
